---
- name: Update package cache
  yum:
    update_cache: yes


- name: Install additional useful tools
  yum:
    name:
      - awscli
      - htop
      - jq
      - mariadb1011          # MySQL client
      - postgresql15         # PostgreSQL client (psql)
      - python3
      - python3-pip
      - redis6
      - tcpdump
      - vim
      - wget
    state: present
