- name: packages for yum and python
  import_tasks: ./00-packages.yaml
  tags: packages

- name: DB connection script (MySQL)
  import_tasks: ./10-db-connect.yaml
  tags: packages

- name: PostgreSQL connection script
  import_tasks: ./11-pg-connect.yaml
  tags: packages

- name: Disable update-motd timer
  systemd:
    name: update-motd.timer
    enabled: no
    state: stopped
